import "~/styles/globals.css";

import { type Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "~/components/theme-provider";
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});
import { ReactQueryProvider } from "~/components/react-query-provider";

export const metadata: Metadata = {
  title: "CopperLens",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/assets/brand/logo.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={poppins.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
