import "~/styles/globals.css";

import { HydrationBoundary, QueryClientProvider } from "@tanstack/react-query";
import { type Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "~/components/theme-provider";
import queryClient from "./hooks";
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "CopperLens",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/assets/brand/logo.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <QueryClientProvider client={queryClient}>
          <HydrationBoundary>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </HydrationBoundary>
        </QueryClientProvider>
      </body>
    </html>
  );
}
